export const GET_MONTH_CALENDAR_SUCCESS = "GET_MONTH_CALENDAR_SUCCESS";
export const GET_MONTH_CALENDAR_ERROR = "GET_MONTH_CALENDAR_ERROR";
export const GET_FILTER_EVENT_TYPE_SUCCESS = "GET_FILTER_EVENT_TYPE_SUCCESS";
export const GET_FILTER_EVENT_TYPE_ERROR = "GET_FILTER_EVENT_TYPE_ERROR";
